### ISSUE TITLE
Other (like gdrive) possibly to exchange stations

### ISSUE THREAD

**Issue by Dtrieb** [ChernyshovYuriy/OpenRadio#23]
Any other possibilities for exchange stations?

Like QR-Code, Nearby Share or something like that?

**Comment by ChernyshovYuriy** [comment]
The intention behind GDrive is one click action, either save or read.
I don't own any server service to replicate such behavior. Might be I need to implement one :-)

**Comment by Dtrieb** [comment]
No I think something like that:
https://github.com/Mohnish226/SendIt

**Comment by ChernyshovYuriy** [comment]
Oh, that is 6 years old project and for Android (with dynamic changes) it is too much. I really like one action button, less user interactions, less interfaces, more intuitive approach. Exactly like GDrive, if only it is available on any Android platform.

**Comment by Jerther** [comment]
What is the use case (functional need) for the google drive feature? I may by able to make suggestions.

**Comment by ChernyshovYuriy** [comment]
back up data created by Open Radio and associated with the current profile of the user (google account), so user can only press Upload and data backed up. On next device user can just click Download.

**Comment by Dtrieb** [comment]
Like this:
https://github.com/myvsparth/flutter_gdrive

**Comment by Jerther** [comment]
Could these Android mechanisms (that are targeted at this use case) be good candidates?

https://developer.android.com/guide/topics/data/autobackup

https://developer.android.com/guide/topics/data/keyvaluebackup

**Comment by ChernyshovYuriy** [comment]
> Like this: https://github.com/myvsparth/flutter_gdrive

That is same GDrive at the end :-)

**Comment by ChernyshovYuriy** [comment]
> Could these Android mechanisms (that are targeted at this use case) be good candidates?
> 
> https://developer.android.com/guide/topics/data/autobackup
> 
> https://developer.android.com/guide/topics/data/keyvaluebackup
> 
> Taken from this general article: https://developer.android.com/guide/topics/data/backup

Yes, this is exactly what i do - Backup data is stored in a private folder in the user's Google Drive account.
But Google restricted access to GDrive from Google TV :-(

**Comment by ChernyshovYuriy** [comment]
This might work differently though:
https://developer.android.com/guide/topics/data/keyvaluebackup
But, what about Android system without GAccount, people can install apk on any Android device, included without account.

**Comment by Jerther** [comment]
Some more info targetted at users on how Android backups are handled: https://support.google.com/android/answer/2819582?sjid=4119838678453573063-NA

I hope that helps :)

**Comment by ChernyshovYuriy** [comment]
> For people without a google account, well at the moment they need one to backup their files to Google Drive anyway, right?

No, there is no back up option for such vases. There is some demand for the feature but I can't settle down requirements.

**Comment by ChernyshovYuriy** [comment]
Unfortunately, back up feature is not an option. It doesn't have public API to back up and restore, the manager handles by the system, base don internal factors. For example, when app installed, the back up manager looking for some conditions to perform back up, so it is system driven. That is the major drawback ...
I can probably implement my own service but the question is, how to identify the user? By email associated with GAccount? Then I will face all issues related to privacy from Google, from users, because sharing email is a private action (while GDrive does it with all necessary pop up and terms or conditions).
I might look into Dropbox option, but user have to have Dropbox account then.

**Comment by Jerther** [comment]
Hmmm I understand.

Here are some other ideas, which are more involved:

- Your own online service, with your own credential system (usually email + password). Then you have to worry about privacy and security, and ideally implement some sort of multifactor authentication if you think the data sensibility is worth it.
- Implement support for dropbox or other online storage, but worry about their privacy policies.
- Implement support for self-hosted services, like ownCloud. This is really nice but a lot more niche. I wouldn't expect a lot of users to use this.
- @Dtrieb suggested QR Codes. This might be my favorite option of the 4 here. Some offline data can be stored in a big QR Code itself. You might be able to show a QR Code that contains all the data to export, and have another phone scan that code to import the data. If there's too much data for one code, you could batch the data into multiple QR codes. See how [Google Authenticator uses QR Codes to export its accounts](https://passwordbits.com/how-to-back-up-the-google-authenticator-app/). This is pretty much maintenance-free as you wouldn't have to depend on any external service, and no worry about privacy.

**Comment by ChernyshovYuriy** [comment]
QR Code sounds like a good option but what if device dont have camera, such as TV or Car or other embedded device running Android. I think these are main clients of such feature,otherwise - Google Drive works fine. The same is related to Near By - what if device dont have Bluetooth chip?
The main point of Google Drive is to share Radio Stations between devices and those devices might not necessary locate in same area, such as house.
Internet (custom web service) is the only option - but then how to identify a user? ...

**Comment by ChernyshovYuriy** [comment]
I understand Google motivation behind restricting GDrive for TV - TV design for large screens with interactions via remote control, TV store has apps specifically designed for streaming (no file apps, no other non TV apps), TV space on disk is limited and hardware in general a bit different from phones, etc ...
I tried DropBox library - TV dont have browser for authorization, neither it has Dropbox native app ...
The same might apply to Cars.
The only way is custom service to upload / download data associated with users email, which he/she would have to provide.
Might be questions from users as to privacy of email though, but I see no other way to transfer Open Radio data from one device to another.

**Comment by ChernyshovYuriy** [comment]
Or let the user select unique password to associated its data within the custom service.
I think this is the most feasible option. Service will verify password to be unique before accept.

**Comment by ChernyshovYuriy** [comment]
I might charge for such feature though :-( I dont think I can find free reliable web service. Google provide its service to host web services, need to see their prices.

**Comment by ChernyshovYuriy** [comment]
Ok, seems like Google Firestone is an excellent choice for this task. No server side code needed. Google takes care of it. Google has Kotlin SDK to perform queries to the database. Nice.
https://firebase.google.com/docs/firestore

**Comment by ChernyshovYuriy** [comment]
Even better news. I might use Free Plan :-) I dont think Open Radio can reach 50K users daily. Currently it is between 5K and 8K.
https://firebase.google.com/pricing?authuser=0&_gl=1*jjuedh*_ga*NjQ3NTM0OTU5LjE2NzcwMjA5NzU.*_ga_CW55HF8NVT*MTY5Nzg1NTA5Ny4xNTcuMS4xNjk3ODU1NTY5LjMxLjAuMA..

**Comment by Jerther** [comment]
Firebase looks promising! Excellent!

**Comment by ChernyshovYuriy** [comment]
Ok, good news, seems like it works!
Firebase provides a lot of services, some are free, some are not. So far, with less then 50K users I seems like get free service.
Fire base provides authorization service as well as I need to authorize user. Enter any Email / password and remember it as it is your account for Open Radio. Service hosted by Google with all benefits.
Then, the same buttons - Upload and Download. Please try on your TV devices. You can save from phone and download from TV, as example.

[tv-release.zip](https://github.com/ChernyshovYuriy/OpenRadio/files/13062045/tv-release.zip)

**Comment by ChernyshovYuriy** [comment]
Actually, you better user real email, because I see a way to restore password if forgotten. Restore link will be sent to account email :-) 
Might not be necessary on current stage as I only do testing of the Firebase and can do everything manually with the Account, but keep in mind.

**Comment by ChernyshovYuriy** [comment]
Any feedback guys?

**Comment by Dtrieb** [comment]
Let's give it a try.

**Comment by Dtrieb** [comment]
> Ok, good news, seems like it works! Firebase provides a lot of services, some are free, some are not. So far, with less then 50K users I seems like get free service. Fire base provides authorization service as well as I need to authorize user. Enter any Email / password and remember it as it is your account for Open Radio. Service hosted by Google with all benefits. Then, the same buttons - Upload and Download. Please try on your TV devices. You can save from phone and download from TV, as example.
> 
> [tv-release.zip](https://github.com/ChernyshovYuriy/OpenRadio/files/13062045/tv-release.zip)
> 
> [release.zip](https://github.com/ChernyshovYuriy/OpenRadio/files/13064690/release.zip)

Yes I try this and it's works for me. (Smartphone and TV)

But how can I logout and/or change my password now?

**Comment by ChernyshovYuriy** [comment]
There are options to Sign Out or Reset Password, I just need to add those, probably to dedicated Account Dialog.
Good thing it works, but it gives complexity to Open Radio, now with Account management ...
I do a proper release then once I will done with changes.

**Comment by ChernyshovYuriy** [comment]
I submitted version 14 to Google :-) 
Funny thing, Firebase has a lot of services: Auth (logic, etc ...), Storage, Crash reports, etc ... and Firebase is the same Google.
GDrive doesnt work but Firebase does.

**Comment by ChernyshovYuriy** [comment]
Change is released.
Thanks for the support!

**Comment by Jerther** [comment]
I just tested the registration on my phone. Here are my observations:
- The email and passwords trigger my password manager (Bitwarden), but it fails to fill the fields. [More info](https://bitwarden.com/help/auto-fill-android/).
- Once the fields are filled, the app enters some kind of glitchy state where the fields are empty, there is no button on the register form and I must do a back action a couple of times. Then the app seems connected and I can see the disconnect, upload and download buttons
- When I use the disconnect button, the email address and disconnect button disapear, but the upload and download buttons are still there. I have to do a back action to make the form disapear. Then I can reconnect normally.

That's it for now. Should I create seperate issues?

**Comment by ChernyshovYuriy** [comment]
Thanks for the feedback.
- I dont use any 3-rd party applications to manage credentials, so I think the issues it cause is out of my control
- That is strange. Maybe consequence of use 3-rd party Password manager? I tested on phone devices as well on various emulators from Google for TV and Automotive, Those just input fields without any logic.
- That is expected behavior, I am trying to provide less text and buttons. Just press on Upload or Download and you will get Login view back.

**Comment by Jerther** [comment]
Ok I did some more tests. I think most of my confusion is caused by the (unusual IMO) flow of modals. But I get it now. I'm fine :)

So the only real problem is with the password manager. When I click on either login fields, the password manager pops up, I select my account, the password manager goes away and another login modal pops up in openradio, this one empty. I can click outside this modal to close it, and the previous one shows up, with the fields filled in (although the password is not masked). I can then hit the Sign In button, and it works.

I have a theory. Bitwarden can sometimes try to activate a "sign in" button after it fills the credential fields. In this case, maybe it clicks on the wrong button, or simulates an "enter" key or something, and that makes another login modal appear.

[Here's a screencast](https://photos.app.goo.gl/cpYa6o4QTgT9v68J9)

By the way, my phone is a Pixel 6 Pro, running Android 14.

**Comment by ChernyshovYuriy** [comment]
I hit the issue you described ... weird :-( the fields are empty indeed. Will fix it.

**Comment by ChernyshovYuriy** [comment]
Change now released,please test the latest version and thanks for the report!
Please, feel free to open issue of any type.

**Comment by Jerther** [comment]
Excellent! And good work!

Now I can get my password manager to fill the fields. There are two minor things left:
- When I click one of the two login fields, my keyboard (base android keyboard) offers me to unlock my password manager, as expected. When I do, it brings me the password manager unlock screen, but at this point I think OpenRadio crashes in the background. I can unlock my manager, and select the appropriate credentials, but then the password manager returns to my android home screen instead of openradio. If I relaunch open radio, it shows the main screen. I've been able to replroduce this issue in another way: launch open radio, and go into the cloud storage menu. The login modal shows (email and password fields). Leave it there, and switch to another app (in my case I swipe up from the bottom of the screen, this shows all my running apps. I select another app and it becomes focused). Now do the same to return to open radio: open radio either returns to its main screen, or I think I saw it crash once or twice.
- Also, when my password manager is already unlocked, the android keyboard suggest the available credentials directly in the keyboard and if I use one of these, then the fields are directly and correctly filled in open radio without the manager opening, and I can sign in. However, the password field becomes unmasked. I can manually erase its content, and type manually and it stays unmasked.

No big deal really in either of these situations. I can live with it :) Please feel free to ask me to open separate github issues with these if it's better for you.
