### ISSUE TITLE
Steering wheel controls to scroll through Favourites [Enhancement] 

### ISSUE THREAD

**Issue by Mattmann19** [ChernyshovYuriy/OpenRadio#39]
Hi, love the App - it's a big improvement on the default Radio app supplied in my AAOS car.

Currently the buttons on the car steering wheel allow me to change radio station to the next station available alphabetically from the 1,000's it can find.

Would it be possible to change this so that it's context sensitive, e.g. if you are in your 'Favourites' list in the App then you scroll through the Favourites in order?

Thanks.

**Comment by ChernyshovYuriy** [comment]
Hi, the behavior of the AAOS is driven by Google.
The buttons should navigate you through the list of the currently selected playing list. It can't scroll through the list that is just visible, for example when you just tap another tab and see the stations, you have to select one from the list in order to load the list. This is how it works. If your task is to change this behavior then I can't help with that.

**Comment by Mattmann19** [comment]
Perfect - thanks for explaining.
